title: "My Data ML Project Blog"
description: "A blog about machine learning and statistics"
theme: minima  # Or any GitHub-supported theme
baseurl: "/data-ml-project"
url: "https://zenahmad06.github.io"
plugins:
  - jekyll-feed
