title: "My Jekyll Blog"
baseurl: "/data-ml-project"  # Leave empty if at the root, use "/data-exploration" if inside a subfolder
url: "https://yourusername.github.io/data-ml-project"
theme: minima  # Or any theme you use

