
title: "My Jekyll Blog"
baseurl: "/data-ml-project"  # Leave blank if at root, else use "/repo-name"
url: "https://zenahmad06.github.io"

# Theme (Minima is a simple default Jekyll theme)
theme: minima
